### PR TITLE
Document containers

### PR DESCRIPTION
**Pull request by dealloc**
This PR adds additional documentation for running the application in Docker/Podman containers.
It also adds a build flag to the Dockerfile so that OpenAPI support (Swagger and JSON files) can be bundled in the container (off by default, since we don't serve it on the hosted version)

### CODE REVIEW

**Comment by dealloc** [comment]
set to draft as we're awaiting feedback for #46

**Comment by dealloc** [comment]
also contemplating if this should be blocked by #70 as I feel rate limits may be one of the main reasons to self host, so having this documented is definitely a must

**Comment by stnokott** [comment]
As mentioned by @dealloc in #72, the `OPENAPI=true` buildarg does not enable the SwaggerUI.

While it's easily possible to take the OpenAPI spec at `/Helldivers-2-API.json` and put that into any regular Swagger Editor, I would love to have the SwaggerUI directly available within the container for simplicity sake.

It's not a major concern, but it would save some clicks when the API changes.

Thanks for the great work on the `docs/containers.md` documentation!

**Comment by dealloc** [comment]
> As mentioned by @dealloc in #72, the `OPENAPI=true` buildarg does not enable the SwaggerUI.
> 
> While it's easily possible to take the OpenAPI spec at `/Helldivers-2-API.json` and put that into any regular Swagger Editor, I would love to have the SwaggerUI directly available within the container for simplicity sake.
> 
> It's not a major concern, but it would save some clicks when the API changes.
> 
> Thanks for the great work on the `docs/containers.md` documentation!

that was an easy fix, 1ae220f should address this by just copying all openapi files rather than just the spec files

**Comment by dealloc** [comment]
as confirmed in https://github.com/helldivers-2/api/issues/46#issuecomment-2051747039 and #72 this PR is now available for review 🥳

**Comment by stnokott** [comment]
> was an easy fix, [1ae220f](https://github.com/helldivers-2/api/commit/1ae220fc256c518b34046eb2b38f66c604957f96) should address this by just copying all openapi files rather than just the spec files

Where is the SwaggerUI available under?

`wwwroot` doesn't contain the `swagger-ui.html` after building with 1ae220f.
Build log also looks suspiciously empty: 

```
#19 [api build 13/14] RUN if [[ "true" = 'true' ]];   then     echo "OPENAPI is set to true, running OpenAPI generators"     && dotnet build "Helldivers-2-API.csproj" --no-restore -c Debug     && mkdir -p wwwroot     && cp /docs/openapi/* wwwroot/   ; fi
#19 0.190 OPENAPI is set to true, running OpenAPI generators
#19 0.346 MSBuild version 17.9.8+b34f75857 for .NET
#19 2.143   Helldivers-2-SourceGen -> /src/Helldivers-2-SourceGen/bin/Debug/netstandard2.0/Helldivers-2-SourceGen.dll
#19 3.353   Helldivers-2-Models -> /src/Helldivers-2-Models/bin/Debug/net8.0/Helldivers-2-Models.dll
#19 3.612   Helldivers-2-Core -> /src/Helldivers-2-Core/bin/Debug/net8.0/Helldivers-2-Core.dll
#19 3.913   Helldivers-2-Sync -> /src/Helldivers-2-Sync/bin/Debug/net8.0/Helldivers-2-Sync.dll
#19 4.951   Helldivers-2-API -> /src/Helldivers-2-API/bin/Debug/net8.0/Helldivers-2-API.dll
#19 4.956   
#19 4.956   GenerateOpenApiDocuments:
#19 4.956     dotnet "/root/.nuget/packages/microsoft.extensions.apidescription.server/8.0.3/build/../tools/dotnet-getdocument.dll" --assembly "/src/Helldivers-2-API/bin/Debug/net8.0/Helldivers-2-API.dll" --file-list "obj/Helldivers-2-API.OpenApiFiles.cache" --framework ".NETCoreApp,Version=v8.0" --output "/docs/openapi" --project "Helldivers-2-API" --assets-file "/src/Helldivers-2-API/obj/project.assets.json" --platform "AnyCPU"
#19 5.323   warn: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[16]
#19 5.323         The WebRootPath was not found: /src/Helldivers-2-API/wwwroot. Static files may be unavailable.
#19 5.356   Generating document named 'v1'.
#19 5.650   Writing document named 'v1' to '/docs/openapi/Helldivers-2-API.json'.
#19 5.650   Generating document named 'arrowhead'.
#19 5.673   Writing document named 'arrowhead' to '/docs/openapi/Helldivers-2-API_arrowhead.json'.
#19 5.686
#19 5.687 Build succeeded.
#19 5.687     0 Warning(s)
#19 5.687     0 Error(s)
#19 5.687
#19 5.687 Time Elapsed 00:00:05.20
#19 DONE 5.7s
```

**Comment by dealloc** [comment]
oops, looks like that's on me
I forgot to copy the OpenAPI files in the build container before copying them, will fix that right away

**Comment by dealloc** [comment]
@stnokott could you verify if the last 2 commits fixed the issue of Swagger not being available?

**Comment by stnokott** [comment]
> @stnokott could you verify if the last 2 commits fixed the issue of Swagger not being available?

Fixed!

All my needs are satisfied now 😄

**Comment by stnokott** [comment]
Thanks for the swift fixes!

**Comment by dealloc** [comment]
@chatterchats looks this is all ready for you then!

**Review by chatterchats — APPROVED** [review]
Ayo, documentation? Imagine!

**Pull request merged**
