### PR TITLE
export metrics to Prometheus

### LINKED ISSUE #84: [FEATURE]: Report metrics on Fly
### What problem does it solve
Provide more in-depth metrics on the runtime of the application (which apps use the API, users, syncs, errors etc)

### What is the solution
Implement Prometheus reporting so Fly picks them up

### Existing alternatives
none

### Added value
More statistics available and better insights in usage and monitoring

### Additional notes
- https://fly.io/docs/metrics-and-logs/metrics/#custom-metrics
- https://github.com/prometheus-net/prometheus-net

### PR DESCRIPTION
**Pull request by dealloc**
this PR adds Prometheus metrics which provides additional metrics for Fly metrics.
The goal is to have more graphs and information on usage of the API

fix #84

### CODE REVIEW

**Review by chatterchats — APPROVED** [review]
I don't see any issues, good feature +1 Approved @lambstream

**Review by lambstream — COMMENTED** [review]
We lose the log of when all information has been synced as far as i can tell on this early morning code review?

**Comment by dealloc** [comment]
> We lose the log of when all information has been synced as far as i can tell on this early morning code review?

Fly keeps those logs AFAIK, and this PR doesn't change anything about how it's stored but rather it provides additional metrics to Fly

**Review by lambstream — APPROVED** [review]

**Comment by lambstream** [comment]
> > We lose the log of when all information has been synced as far as i can tell on this early morning code review?
> 
> Fly keeps those logs AFAIK, and this PR doesn't change anything about how it's stored but rather it provides additional metrics to Fly

Alrighty then 😁

**Pull request merged**
